### ISSUE TITLE
Send emails to team leaders also.

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/bz-commendations-next#85]
```[tasklist]
### Tasks
- [x] Create Leader Table
- [x] Select Leader for User's Group
- [x] Send Email to Leader
```
